# Generated by Django 4.2.11 on 2026-07-01 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('tag', models.CharField(choices=[('movement', 'Movement'), ('stillness', 'Stillness'), ('rest', 'Rest'), ('breath', 'Breath')], max_length=20)),
                ('tagline', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('typical_duration_minutes', models.PositiveIntegerField(default=60)),
                ('intensity', models.PositiveSmallIntegerField(default=3, help_text='1–5')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudioInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Stillpoint', max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('address_line_1', models.CharField(default='147 Almond Street', max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(default='Oakland', max_length=80)),
                ('state', models.CharField(default='CA', max_length=40)),
                ('postal_code', models.CharField(default='94610', max_length=20)),
                ('phone', models.CharField(default='(510) 555-0147', max_length=40)),
                ('email', models.EmailField(default='hello@stillpoint.studio', max_length=254)),
                ('hours', models.CharField(default='Open daily · 6:30am – 8:30pm', max_length=120)),
                ('founded_year', models.PositiveSmallIntegerField(default=2014)),
            ],
            options={
                'verbose_name': 'Studio info',
                'verbose_name_plural': 'Studio info',
            },
        ),
        migrations.CreateModel(
            name='StudioRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveSmallIntegerField(default=12)),
                ('has_natural_light', models.BooleanField(default=True)),
                ('is_skylit', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(help_text="e.g. 'Vinyasa · 14 years'", max_length=80)),
                ('discipline', models.CharField(help_text="e.g. 'Slow flow, breath-led'", max_length=80)),
                ('why_i_teach', models.TextField(help_text='Personal statement shown on hover')),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='teachers/')),
                ('photo_url', models.URLField(blank=True, help_text='External image if no upload')),
                ('years_teaching', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('practices', models.ManyToManyField(blank=True, related_name='teachers', to='studio.practice')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='YogaClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('capacity_override', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('subtitle', models.CharField(blank=True, help_text="e.g. 'Slow Flow'", max_length=120)),
                ('description_override', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='studio.practice')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='studio.studioroom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='studio.teacher')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='practice',
            name='default_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practices', to='studio.studioroom'),
        ),
        migrations.CreateModel(
            name='FreeClassRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('preferred_practice', models.CharField(blank=True, choices=[('vinyasa', 'Vinyasa — slow flow'), ('yin', 'Yin — long holds'), ('restorative', 'Restorative — fully supported'), ('breathwork', 'Breathwork — seated'), ('unsure', 'Not sure yet')], max_length=20)),
                ('preferred_time', models.CharField(blank=True, choices=[('weekday-am', 'Weekday mornings'), ('weekday-pm', 'Weekday evenings'), ('weekend', 'Weekends'), ('any', 'Anytime')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('booked', 'Booked'), ('closed', 'Closed')], default='new', max_length=12)),
                ('internal_notes', models.TextField(blank=True, help_text='Staff-only notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='studio_free_status_db0f72_idx')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(help_text='The concrete date of the class')),
                ('student_name', models.CharField(max_length=160)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('is_first_class', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('waitlist', 'Waitlist'), ('cancelled', 'Cancelled'), ('noshow', 'No-show')], default='confirmed', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('yoga_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='studio.yogaclass')),
            ],
            options={
                'ordering': ['-session_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='yogaclass',
            constraint=models.UniqueConstraint(fields=('day_of_week', 'start_time', 'room'), name='unique_weekly_slot_per_room'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['session_date', 'status'], name='studio_book_session_862f44_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['yoga_class', 'session_date'], name='studio_book_yoga_cl_d0f431_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('yoga_class', 'session_date', 'student_email'), name='unique_active_booking_per_email_per_session'),
        ),
    ]
