# Generated by Django 4.2.11 on 2026-07-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeclassrequest',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=40),
        ),
    ]
